name: GitHub Actions Demo
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - run: pip install scipy
      - run: git clone https://github.com/diku-dk/futhark && cd futhark && stack setup && stack build && stack install
      - run: python test_pmn.py

